---
# handlers file for setup-apache
    - name: start apache
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: "'RedHat' in ansible_distribution"
    - name: start apache2
      systemd:
        name: apache2
        state: started
        enabled: yes
      when: "'Ubuntu' in ansible_distribution"
    - name : restart httpd
      systemd:
        name: httpd
        state: restarted
    - name : restart apache2
      systemd:
        name: apache2
        state: restarted

